name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version that should be released"
        required: true
        type: string
  push:
    tags:
      - '*'

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.5.0
        with:
          pkgname: mondoo
          pkgbuild: ./mondoo/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ github.event.inputs.version }}
          force_push: 'true'